### ISSUE TITLE
chore: Fix eslint issues and and pre-push lint hook

### ISSUE THREAD

**Issue by rackstar** [NexusMutual/sdk#112]
## Overview

* The eslint was not properly configured and there is quite a few linting issues that needs to be addressed.
   * add prepush hooks to automatically run linting checks 
* Should we rename the files to kebab-case to be inline with the rest of our repos?

**Comment by Gideonnn** [comment]
I see the appeal in pre-push hooks, but I find they slow you down more than they add value. Running tests/linting on semi-big and big projects can take quite a while, so everybody will use `--no-verify` at some point.

Build minutes are cheap and CI is a way better place to check for stuff like this, because nobody can skip it and passing ci can be used as a requirement for merging. Pre-push hooks are just sugar and give no guarantees
